# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Core
else:
    import _Core

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class RTTI(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, classname, parent=None):
        _Core.RTTI_swiginit(self, _Core.new_RTTI(classname, parent))

    def __eq__(self, other):
        return _Core.RTTI___eq__(self, other)

    def __ne__(self, other):
        return _Core.RTTI___ne__(self, other)

    def parent(self):
        return _Core.RTTI_parent(self)

    def className(self):
        return _Core.RTTI_className(self)

    def before(self, other):
        return _Core.RTTI_before(self, other)

    def isTypeOf(self, other):
        return _Core.RTTI_isTypeOf(self, other)
    __swig_destroy__ = _Core.delete_RTTI

# Register RTTI in _Core:
_Core.RTTI_swigregister(RTTI)

class PropertyNotFoundException(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.PropertyNotFoundException_swiginit(self, _Core.new_PropertyNotFoundException(*args))
    __swig_destroy__ = _Core.delete_PropertyNotFoundException

# Register PropertyNotFoundException in _Core:
_Core.PropertyNotFoundException_swigregister(PropertyNotFoundException)

class MetaEnum(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Core.delete_MetaEnum

    def keyCount(self):
        return _Core.MetaEnum_keyCount(self)

    def key(self, index):
        return _Core.MetaEnum_key(self, index)

    def valueToKey(self, value):
        return _Core.MetaEnum_valueToKey(self, value)

    def keyToValue(self, key):
        return _Core.MetaEnum_keyToValue(self, key)

# Register MetaEnum in _Core:
_Core.MetaEnum_swigregister(MetaEnum)

class MetaProperty(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.MetaProperty_swiginit(self, _Core.new_MetaProperty(*args))
    __swig_destroy__ = _Core.delete_MetaProperty

    def setInfo(self, name, type, isArray, isClass, isIndex, isReference, isOptional, isEnum, enumeration=None):
        return _Core.MetaProperty_setInfo(self, name, type, isArray, isClass, isIndex, isReference, isOptional, isEnum, enumeration)

    def name(self):
        return _Core.MetaProperty_name(self)

    def type(self):
        return _Core.MetaProperty_type(self)

    def enumerator(self):
        return _Core.MetaProperty_enumerator(self)

    def isArray(self):
        return _Core.MetaProperty_isArray(self)

    def isClass(self):
        return _Core.MetaProperty_isClass(self)

    def isIndex(self):
        return _Core.MetaProperty_isIndex(self)

    def isReference(self):
        return _Core.MetaProperty_isReference(self)

    def isEnum(self):
        return _Core.MetaProperty_isEnum(self)

    def isOptional(self):
        return _Core.MetaProperty_isOptional(self)

    def createClass(self):
        return _Core.MetaProperty_createClass(self)

    def arrayElementCount(self, object):
        return _Core.MetaProperty_arrayElementCount(self, object)

    def arrayObject(self, object, i):
        return _Core.MetaProperty_arrayObject(self, object, i)

    def arrayAddObject(self, object, child):
        return _Core.MetaProperty_arrayAddObject(self, object, child)

    def arrayRemoveObject(self, *args):
        return _Core.MetaProperty_arrayRemoveObject(self, *args)

    def write(self, object, value):
        return _Core.MetaProperty_write(self, object, value)

    def writeString(self, object, value):
        return _Core.MetaProperty_writeString(self, object, value)

    def read(self, object):
        return _Core.MetaProperty_read(self, object)

    def readString(self, object):
        return _Core.MetaProperty_readString(self, object)

# Register MetaProperty in _Core:
_Core.MetaProperty_swigregister(MetaProperty)

class MetaObject(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, rtti, base=None):
        _Core.MetaObject_swiginit(self, _Core.new_MetaObject(rtti, base))
    __swig_destroy__ = _Core.delete_MetaObject

    def rtti(self):
        return _Core.MetaObject_rtti(self)

    def base(self):
        return _Core.MetaObject_base(self)

    def propertyCount(self):
        return _Core.MetaObject_propertyCount(self)

    def property(self, *args):
        return _Core.MetaObject_property(self, *args)

# Register MetaObject in _Core:
_Core.MetaObject_swigregister(MetaObject)

class TimeSpan(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.TimeSpan_swiginit(self, _Core.new_TimeSpan(*args))

    def __eq__(self, arg2):
        return _Core.TimeSpan___eq__(self, arg2)

    def __ne__(self, arg2):
        return _Core.TimeSpan___ne__(self, arg2)

    def __lt__(self, arg2):
        return _Core.TimeSpan___lt__(self, arg2)

    def __le__(self, arg2):
        return _Core.TimeSpan___le__(self, arg2)

    def __gt__(self, arg2):
        return _Core.TimeSpan___gt__(self, arg2)

    def __ge__(self, arg2):
        return _Core.TimeSpan___ge__(self, arg2)

    def __add__(self, arg2):
        return _Core.TimeSpan___add__(self, arg2)

    def __sub__(self, arg2):
        return _Core.TimeSpan___sub__(self, arg2)

    def __iadd__(self, arg2):
        return _Core.TimeSpan___iadd__(self, arg2)

    def __isub__(self, arg2):
        return _Core.TimeSpan___isub__(self, arg2)

    def abs(self):
        return _Core.TimeSpan_abs(self)

    def seconds(self):
        return _Core.TimeSpan_seconds(self)

    def microseconds(self):
        return _Core.TimeSpan_microseconds(self)

    def length(self):
        return _Core.TimeSpan_length(self)

    def set(self, seconds):
        return _Core.TimeSpan_set(self, seconds)

    def setUSecs(self, arg2):
        return _Core.TimeSpan_setUSecs(self, arg2)

    def elapsedTime(self, days, hours=None, minutes=None, seconds=None):
        return _Core.TimeSpan_elapsedTime(self, days, hours, minutes, seconds)

    def toDouble(self):
        return _Core.TimeSpan_toDouble(self)

    def __float__(self):
            return self.length()

    __swig_destroy__ = _Core.delete_TimeSpan

# Register TimeSpan in _Core:
_Core.TimeSpan_swigregister(TimeSpan)
cvar = _Core.cvar
TimeSpan.MinTime = _Core.cvar.TimeSpan_MinTime
TimeSpan.MaxTime = _Core.cvar.TimeSpan_MaxTime

class Time(TimeSpan):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.Time_swiginit(self, _Core.new_Time(*args))

    def __nonzero__(self):
        return _Core.Time___nonzero__(self)
    __bool__ = __nonzero__



    def __add__(self, arg2):
        return _Core.Time___add__(self, arg2)

    def __sub__(self, *args):
        return _Core.Time___sub__(self, *args)

    def __iadd__(self, arg2):
        return _Core.Time___iadd__(self, arg2)

    def __isub__(self, arg2):
        return _Core.Time___isub__(self, arg2)

    def set(self, year, month, day, hour, min, sec, usec):
        return _Core.Time_set(self, year, month, day, hour, min, sec, usec)

    def get(self):
        return _Core.Time_get(self)

    def get2(self):
        return _Core.Time_get2(self)

    @staticmethod
    def LocalTime():
        return _Core.Time_LocalTime()

    @staticmethod
    def LocalTimeZone():
        return _Core.Time_LocalTimeZone()

    @staticmethod
    def GMT():
        return _Core.Time_GMT()

    @staticmethod
    def FromYearDay(year, year_day):
        return _Core.Time_FromYearDay(year, year_day)

    def localTimeZoneOffset(self):
        return _Core.Time_localTimeZoneOffset(self)

    def localtime(self):
        return _Core.Time_localtime(self)

    def gmt(self):
        return _Core.Time_gmt(self)

    def toLocalTime(self):
        return _Core.Time_toLocalTime(self)

    def toGMT(self):
        return _Core.Time_toGMT(self)

    def valid(self):
        return _Core.Time_valid(self)

    def toString(self, fmt):
        return _Core.Time_toString(self, fmt)

    def iso(self):
        return _Core.Time_iso(self)

    def fromString(self, str, fmt):
        return _Core.Time_fromString(self, str, fmt)

    @staticmethod
    def FromString(str, fmt):
        return _Core.Time_FromString(str, fmt)

    def __str__(self):
            return self.toString("%Y-%m-%d %H:%M:%S.%f000000")[:23]

    __swig_destroy__ = _Core.delete_Time

# Register Time in _Core:
_Core.Time_swigregister(Time)
Time.Null = _Core.cvar.Time_Null

def Time_LocalTime():
    return _Core.Time_LocalTime()

def Time_LocalTimeZone():
    return _Core.Time_LocalTimeZone()

def Time_GMT():
    return _Core.Time_GMT()

def Time_FromYearDay(year, year_day):
    return _Core.Time_FromYearDay(year, year_day)

def Time_FromString(str, fmt):
    return _Core.Time_FromString(str, fmt)

class ValueError(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Core.ValueError_swiginit(self, _Core.new_ValueError())
    __swig_destroy__ = _Core.delete_ValueError

    def what(self):
        return _Core.ValueError_what(self)

# Register ValueError in _Core:
_Core.ValueError_swigregister(ValueError)
Unset = cvar.Unset

class Enumeration(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Core.delete_Enumeration

    def toString(self):
        return _Core.Enumeration_toString(self)

    def fromString(self, str):
        return _Core.Enumeration_fromString(self, str)

    def toInt(self):
        return _Core.Enumeration_toInt(self)

    def fromInt(self, value):
        return _Core.Enumeration_fromInt(self, value)

# Register Enumeration in _Core:
_Core.Enumeration_swigregister(Enumeration)

class GeneralException(Exception):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.GeneralException_swiginit(self, _Core.new_GeneralException(*args))
    __swig_destroy__ = _Core.delete_GeneralException

    def what(self):
        return _Core.GeneralException_what(self)

    def __str__(self):
            return self.what()


# Register GeneralException in _Core:
_Core.GeneralException_swigregister(GeneralException)

class MemoryException(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.MemoryException_swiginit(self, _Core.new_MemoryException(*args))
    __swig_destroy__ = _Core.delete_MemoryException

# Register MemoryException in _Core:
_Core.MemoryException_swigregister(MemoryException)

class StreamException(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.StreamException_swiginit(self, _Core.new_StreamException(*args))
    __swig_destroy__ = _Core.delete_StreamException

# Register StreamException in _Core:
_Core.StreamException_swigregister(StreamException)

class EndOfStreamException(StreamException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.EndOfStreamException_swiginit(self, _Core.new_EndOfStreamException(*args))
    __swig_destroy__ = _Core.delete_EndOfStreamException

# Register EndOfStreamException in _Core:
_Core.EndOfStreamException_swigregister(EndOfStreamException)

class TypeConversionException(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.TypeConversionException_swiginit(self, _Core.new_TypeConversionException(*args))
    __swig_destroy__ = _Core.delete_TypeConversionException

# Register TypeConversionException in _Core:
_Core.TypeConversionException_swigregister(TypeConversionException)

class OverflowException(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.OverflowException_swiginit(self, _Core.new_OverflowException(*args))
    __swig_destroy__ = _Core.delete_OverflowException

# Register OverflowException in _Core:
_Core.OverflowException_swigregister(OverflowException)

class UnderflowException(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.UnderflowException_swiginit(self, _Core.new_UnderflowException(*args))
    __swig_destroy__ = _Core.delete_UnderflowException

# Register UnderflowException in _Core:
_Core.UnderflowException_swigregister(UnderflowException)

class ValueException(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.ValueException_swiginit(self, _Core.new_ValueException(*args))
    __swig_destroy__ = _Core.delete_ValueException

# Register ValueException in _Core:
_Core.ValueException_swigregister(ValueException)

class TypeException(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.TypeException_swiginit(self, _Core.new_TypeException(*args))
    __swig_destroy__ = _Core.delete_TypeException

# Register TypeException in _Core:
_Core.TypeException_swigregister(TypeException)

class ClassNotFound(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.ClassNotFound_swiginit(self, _Core.new_ClassNotFound(*args))
    __swig_destroy__ = _Core.delete_ClassNotFound

# Register ClassNotFound in _Core:
_Core.ClassNotFound_swigregister(ClassNotFound)

class DuplicateClassname(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.DuplicateClassname_swiginit(self, _Core.new_DuplicateClassname(*args))
    __swig_destroy__ = _Core.delete_DuplicateClassname

# Register DuplicateClassname in _Core:
_Core.DuplicateClassname_swigregister(DuplicateClassname)


def intrusive_ptr_add_ref(*args):
    return _Core.intrusive_ptr_add_ref(*args)

def intrusive_ptr_release(*args):
    return _Core.intrusive_ptr_release(*args)
class BaseObject(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.BaseObject_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.BaseObject_TypeInfo()

    def className(self):
        return _Core.BaseObject_className(self)

    def typeInfo(self):
        return _Core.BaseObject_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.BaseObject_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.BaseObject_ConstCast(*args)

    def serialize(self, arg2):
        return _Core.BaseObject_serialize(self, arg2)

    @staticmethod
    def Meta():
        return _Core.BaseObject_Meta()

    def meta(self):
        return _Core.BaseObject_meta(self)
    __swig_destroy__ = _Core.delete_BaseObject

    def clone(self):
        return _Core.BaseObject_clone(self)

    def incrementReferenceCount(self):
        return _Core.BaseObject_incrementReferenceCount(self)

    def decrementReferenceCount(self):
        return _Core.BaseObject_decrementReferenceCount(self)

    def referenceCount(self):
        return _Core.BaseObject_referenceCount(self)

    @staticmethod
    def ObjectCount():
        return _Core.BaseObject_ObjectCount()

# Register BaseObject in _Core:
_Core.BaseObject_swigregister(BaseObject)

def BaseObject_ClassName():
    return _Core.BaseObject_ClassName()

def BaseObject_TypeInfo():
    return _Core.BaseObject_TypeInfo()

def BaseObject_Cast(*args):
    return _Core.BaseObject_Cast(*args)

def BaseObject_ConstCast(*args):
    return _Core.BaseObject_ConstCast(*args)

def BaseObject_Meta():
    return _Core.BaseObject_Meta()

def BaseObject_ObjectCount():
    return _Core.BaseObject_ObjectCount()

class Alarmable(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Core.Alarmable_swiginit(self, _Core.new_Alarmable())
    __swig_destroy__ = _Core.delete_Alarmable

# Register Alarmable in _Core:
_Core.Alarmable_swigregister(Alarmable)

class Interruptible(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Core.Interruptible_swiginit(self, _Core.new_Interruptible())
    __swig_destroy__ = _Core.delete_Interruptible

    @staticmethod
    def Interrupt(sig):
        return _Core.Interruptible_Interrupt(sig)

# Register Interruptible in _Core:
_Core.Interruptible_swigregister(Interruptible)

def Interruptible_Interrupt(sig):
    return _Core.Interruptible_Interrupt(sig)

class OperationInterrupted(GeneralException):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.OperationInterrupted_swiginit(self, _Core.new_OperationInterrupted(*args))
    __swig_destroy__ = _Core.delete_OperationInterrupted

# Register OperationInterrupted in _Core:
_Core.OperationInterrupted_swigregister(OperationInterrupted)

class InterruptibleObject(BaseObject, Interruptible, Alarmable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.InterruptibleObject_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.InterruptibleObject_TypeInfo()

    def className(self):
        return _Core.InterruptibleObject_className(self)

    def typeInfo(self):
        return _Core.InterruptibleObject_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.InterruptibleObject_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.InterruptibleObject_ConstCast(*args)

    def __init__(self):
        _Core.InterruptibleObject_swiginit(self, _Core.new_InterruptibleObject())
    __swig_destroy__ = _Core.delete_InterruptibleObject

# Register InterruptibleObject in _Core:
_Core.InterruptibleObject_swigregister(InterruptibleObject)

def InterruptibleObject_ClassName():
    return _Core.InterruptibleObject_ClassName()

def InterruptibleObject_TypeInfo():
    return _Core.InterruptibleObject_TypeInfo()

def InterruptibleObject_Cast(*args):
    return _Core.InterruptibleObject_Cast(*args)

def InterruptibleObject_ConstCast(*args):
    return _Core.InterruptibleObject_ConstCast(*args)

SC_API_VERSION = _Core.SC_API_VERSION
class Version(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.Version_swiginit(self, _Core.new_Version(*args))

    def majorTag(self):
        return _Core.Version_majorTag(self)

    def minorTag(self):
        return _Core.Version_minorTag(self)

    def toString(self):
        return _Core.Version_toString(self)

    def fromString(self, str):
        return _Core.Version_fromString(self, str)

    @staticmethod
    def pack(major, minor):
        return _Core.Version_pack(major, minor)

    def __eq__(self, other):
        return _Core.Version___eq__(self, other)

    def __ne__(self, other):
        return _Core.Version___ne__(self, other)

    def __lt__(self, other):
        return _Core.Version___lt__(self, other)

    def __gt__(self, other):
        return _Core.Version___gt__(self, other)

    def __le__(self, other):
        return _Core.Version___le__(self, other)

    def __ge__(self, other):
        return _Core.Version___ge__(self, other)
    packed = property(_Core.Version_packed_get, _Core.Version_packed_set)
    __swig_destroy__ = _Core.delete_Version

# Register Version in _Core:
_Core.Version_swigregister(Version)

def Version_pack(major, minor):
    return _Core.Version_pack(major, minor)

class FrameworkVersion(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Core.FrameworkVersion_swiginit(self, _Core.new_FrameworkVersion())

    def toString(self):
        return _Core.FrameworkVersion_toString(self)

    def systemInfo(self):
        return _Core.FrameworkVersion_systemInfo(self)
    __swig_destroy__ = _Core.delete_FrameworkVersion

# Register FrameworkVersion in _Core:
_Core.FrameworkVersion_swigregister(FrameworkVersion)

class GenericArchive(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    NONE = _Core.GenericArchive_NONE
    STATIC_TYPE = _Core.GenericArchive_STATIC_TYPE
    IGNORE_CHILDS = _Core.GenericArchive_IGNORE_CHILDS
    XML_ELEMENT = _Core.GenericArchive_XML_ELEMENT
    XML_CDATA = _Core.GenericArchive_XML_CDATA
    XML_MANDATORY = _Core.GenericArchive_XML_MANDATORY
    DB_TABLE = _Core.GenericArchive_DB_TABLE
    SPLIT_TIME = _Core.GenericArchive_SPLIT_TIME
    INDEX_ATTRIBUTE = _Core.GenericArchive_INDEX_ATTRIBUTE
    __swig_destroy__ = _Core.delete_GenericArchive

    @staticmethod
    def PackVersion(major, minor):
        return _Core.GenericArchive_PackVersion(major, minor)

    def open(self, dataSource):
        return _Core.GenericArchive_open(self, dataSource)

    def create(self, dataSource):
        return _Core.GenericArchive_create(self, dataSource)

    def close(self):
        return _Core.GenericArchive_close(self)

    def setStrictMode(self, strict):
        return _Core.GenericArchive_setStrictMode(self, strict)

    def isStrictMode(self):
        return _Core.GenericArchive_isStrictMode(self)

    def isReading(self):
        return _Core.GenericArchive_isReading(self)

    def success(self):
        return _Core.GenericArchive_success(self)

    def hint(self):
        return _Core.GenericArchive_hint(self)

    def setHint(self, arg2):
        return _Core.GenericArchive_setHint(self, arg2)

    def setValidity(self, arg2):
        return _Core.GenericArchive_setValidity(self, arg2)

    def setVersion(self, v):
        return _Core.GenericArchive_setVersion(self, v)

    def version(self):
        return _Core.GenericArchive_version(self)

    def versionMajor(self):
        return _Core.GenericArchive_versionMajor(self)

    def versionMinor(self):
        return _Core.GenericArchive_versionMinor(self)

    def propertyCount(self):
        return _Core.GenericArchive_propertyCount(self)

    def setProperty(self, name, v):
        return _Core.GenericArchive_setProperty(self, name, v)

    def property(self, name):
        return _Core.GenericArchive_property(self, name)

    def propertyInt(self, name):
        return _Core.GenericArchive_propertyInt(self, name)

    def propertyDouble(self, name):
        return _Core.GenericArchive_propertyDouble(self, name)

    def propertyString(self, name):
        return _Core.GenericArchive_propertyString(self, name)

    def clearProperties(self):
        return _Core.GenericArchive_clearProperties(self)

    def read(self, *args):
        return _Core.GenericArchive_read(self, *args)

    def write(self, *args):
        return _Core.GenericArchive_write(self, *args)

    def readObject(self):
        return _Core.GenericArchive_readObject(self)

    def writeObject(self, obj):
        return _Core.GenericArchive_writeObject(self, obj)

# Register GenericArchive in _Core:
_Core.GenericArchive_swigregister(GenericArchive)

def GenericArchive_PackVersion(major, minor):
    return _Core.GenericArchive_PackVersion(major, minor)

class Status(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    SEISCOMP_SUCCESS = _Core.Status_SEISCOMP_SUCCESS
    SEISCOMP_FAILURE = _Core.Status_SEISCOMP_FAILURE
    SEISCOMP_INVALID_GROUP_ERROR = _Core.Status_SEISCOMP_INVALID_GROUP_ERROR
    SEISCOMP_INVALID_CLIENT_NAME_ERROR = _Core.Status_SEISCOMP_INVALID_CLIENT_NAME_ERROR
    SEISCOMP_TIMEOUT_ERROR = _Core.Status_SEISCOMP_TIMEOUT_ERROR
    SEISCOMP_MESSAGE_SIZE_ERROR = _Core.Status_SEISCOMP_MESSAGE_SIZE_ERROR
    SEISCOMP_ARCHIVE_REQUEST_ERROR = _Core.Status_SEISCOMP_ARCHIVE_REQUEST_ERROR
    SEISCOMP_CONNECT_ERROR = _Core.Status_SEISCOMP_CONNECT_ERROR
    SEISCOMP_NETWORKING_ERROR = _Core.Status_SEISCOMP_NETWORKING_ERROR
    SEISCOMP_NOT_CONNECTED_ERROR = _Core.Status_SEISCOMP_NOT_CONNECTED_ERROR
    SEISCOMP_CLIENT_NAME_NOT_UNIQUE = _Core.Status_SEISCOMP_CLIENT_NAME_NOT_UNIQUE
    SEISCOMP_WRONG_SERVER_VERSION = _Core.Status_SEISCOMP_WRONG_SERVER_VERSION
    SEISCOMP_TOO_MANY_USERS = _Core.Status_SEISCOMP_TOO_MANY_USERS
    SC_QUANTITY = _Core.Status_SC_QUANTITY

    @staticmethod
    def StatusToStr(statusCode):
        return _Core.Status_StatusToStr(statusCode)
    __swig_destroy__ = _Core.delete_Status

# Register Status in _Core:
_Core.Status_swigregister(Status)

def Status_StatusToStr(statusCode):
    return _Core.Status_StatusToStr(statusCode)

class Array(BaseObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.Array_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.Array_TypeInfo()

    def className(self):
        return _Core.Array_className(self)

    def typeInfo(self):
        return _Core.Array_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.Array_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.Array_ConstCast(*args)
    CHAR = _Core.Array_CHAR
    INT = _Core.Array_INT
    FLOAT = _Core.Array_FLOAT
    DOUBLE = _Core.Array_DOUBLE
    DATETIME = _Core.Array_DATETIME
    STRING = _Core.Array_STRING
    COMPLEX_FLOAT = _Core.Array_COMPLEX_FLOAT
    COMPLEX_DOUBLE = _Core.Array_COMPLEX_DOUBLE
    DT_QUANTITY = _Core.Array_DT_QUANTITY
    __swig_destroy__ = _Core.delete_Array

    def dataType(self):
        return _Core.Array_dataType(self)

    def clone(self):
        return _Core.Array_clone(self)

    def copy(self, dt):
        return _Core.Array_copy(self, dt)

    def data(self):
        return _Core.Array_data(self)

    def size(self):
        return _Core.Array_size(self)

    def resize(self, size):
        return _Core.Array_resize(self, size)

    def clear(self):
        return _Core.Array_clear(self)

    def elementSize(self):
        return _Core.Array_elementSize(self)

    def append(self, arg2):
        return _Core.Array_append(self, arg2)

    def slice(self, m, n):
        return _Core.Array_slice(self, m, n)

    def str(self):
        return _Core.Array_str(self)

    def numpy(self):
        return _Core.Array_numpy(self)

    def setNumpy(self, obj):
        return _Core.Array_setNumpy(self, obj)

    def bytes(self):
        return _Core.Array_bytes(self)

    def str(self):
    	""" For backwards compatibility """
    	return self.bytes()

    def __str__(self):
    	""" For backwards compatibility """
    	return self.bytes()

    def __bytes__(self):
    	return self.bytes()

    def numeric(self):
    	import sys
    	sys.stderr.write("Use of Array.numeric() is deprecated - use numpy() instead\n")
    	return self.numpy()


# Register Array in _Core:
_Core.Array_swigregister(Array)

def Array_ClassName():
    return _Core.Array_ClassName()

def Array_TypeInfo():
    return _Core.Array_TypeInfo()

def Array_Cast(*args):
    return _Core.Array_Cast(*args)

def Array_ConstCast(*args):
    return _Core.Array_ConstCast(*args)

class BitSet(BaseObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.BitSet_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.BitSet_TypeInfo()

    def className(self):
        return _Core.BitSet_className(self)

    def typeInfo(self):
        return _Core.BitSet_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.BitSet_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.BitSet_ConstCast(*args)

    def __init__(self, *args):
        _Core.BitSet_swiginit(self, _Core.new_BitSet(*args))

    def __iand__(self, b):
        return _Core.BitSet___iand__(self, b)

    def __ior__(self, b):
        return _Core.BitSet___ior__(self, b)

    def __ixor__(self, b):
        return _Core.BitSet___ixor__(self, b)

    def __isub__(self, b):
        return _Core.BitSet___isub__(self, b)

    def __ilshift__(self, n):
        return _Core.BitSet___ilshift__(self, n)

    def __irshift__(self, n):
        return _Core.BitSet___irshift__(self, n)

    def __lshift__(self, n):
        return _Core.BitSet___lshift__(self, n)

    def __rshift__(self, n):
        return _Core.BitSet___rshift__(self, n)

    def __invert__(self):
        return _Core.BitSet___invert__(self)

    def resize(self, num_bits, value=False):
        return _Core.BitSet_resize(self, num_bits, value)

    def clear(self):
        return _Core.BitSet_clear(self)

    def append(self, bit):
        return _Core.BitSet_append(self, bit)

    def set(self, *args):
        return _Core.BitSet_set(self, *args)

    def reset(self, *args):
        return _Core.BitSet_reset(self, *args)

    def flip(self, *args):
        return _Core.BitSet_flip(self, *args)

    def test(self, n):
        return _Core.BitSet_test(self, n)

    def any(self):
        return _Core.BitSet_any(self)

    def none(self):
        return _Core.BitSet_none(self)

    def numberOfBitsSet(self):
        return _Core.BitSet_numberOfBitsSet(self)

    def toUlong(self):
        return _Core.BitSet_toUlong(self)

    def size(self):
        return _Core.BitSet_size(self)

    def numberOfBlocks(self):
        return _Core.BitSet_numberOfBlocks(self)

    def maximumSize(self):
        return _Core.BitSet_maximumSize(self)

    def empty(self):
        return _Core.BitSet_empty(self)

    def findFirst(self):
        return _Core.BitSet_findFirst(self)

    def findNext(self, pos):
        return _Core.BitSet_findNext(self, pos)

    def impl(self, *args):
        return _Core.BitSet_impl(self, *args)
    __swig_destroy__ = _Core.delete_BitSet

# Register BitSet in _Core:
_Core.BitSet_swigregister(BitSet)

def BitSet_ClassName():
    return _Core.BitSet_ClassName()

def BitSet_TypeInfo():
    return _Core.BitSet_TypeInfo()

def BitSet_Cast(*args):
    return _Core.BitSet_Cast(*args)

def BitSet_ConstCast(*args):
    return _Core.BitSet_ConstCast(*args)

class Record(BaseObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.Record_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.Record_TypeInfo()

    def className(self):
        return _Core.Record_className(self)

    def typeInfo(self):
        return _Core.Record_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.Record_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.Record_ConstCast(*args)

    def serialize(self, ar):
        return _Core.Record_serialize(self, ar)
    META_ONLY = _Core.Record_META_ONLY
    DATA_ONLY = _Core.Record_DATA_ONLY
    SAVE_RAW = _Core.Record_SAVE_RAW
    H_QUANTITY = _Core.Record_H_QUANTITY
    NOT_SIGNED = _Core.Record_NOT_SIGNED
    SIGNATURE_VALIDATED = _Core.Record_SIGNATURE_VALIDATED
    SIGNATURE_VALIDATION_FAILED = _Core.Record_SIGNATURE_VALIDATION_FAILED
    A_QUANTITY = _Core.Record_A_QUANTITY
    __swig_destroy__ = _Core.delete_Record

    def networkCode(self):
        return _Core.Record_networkCode(self)

    def setNetworkCode(self, net):
        return _Core.Record_setNetworkCode(self, net)

    def stationCode(self):
        return _Core.Record_stationCode(self)

    def setStationCode(self, sta):
        return _Core.Record_setStationCode(self, sta)

    def locationCode(self):
        return _Core.Record_locationCode(self)

    def setLocationCode(self, loc):
        return _Core.Record_setLocationCode(self, loc)

    def channelCode(self):
        return _Core.Record_channelCode(self)

    def setChannelCode(self, cha):
        return _Core.Record_setChannelCode(self, cha)

    def startTime(self):
        return _Core.Record_startTime(self)

    def setStartTime(self, time):
        return _Core.Record_setStartTime(self, time)

    def endTime(self):
        return _Core.Record_endTime(self)

    def timeWindow(self):
        return _Core.Record_timeWindow(self)

    def sampleCount(self):
        return _Core.Record_sampleCount(self)

    def samplingFrequency(self):
        return _Core.Record_samplingFrequency(self)

    def timingQuality(self):
        return _Core.Record_timingQuality(self)

    def setTimingQuality(self, tqual):
        return _Core.Record_setTimingQuality(self, tqual)

    def streamID(self):
        return _Core.Record_streamID(self)

    def dataType(self):
        return _Core.Record_dataType(self)

    def setDataType(self, dt):
        return _Core.Record_setDataType(self, dt)

    def setHint(self, h):
        return _Core.Record_setHint(self, h)

    def setAuthentication(self, auth):
        return _Core.Record_setAuthentication(self, auth)

    def authentication(self):
        return _Core.Record_authentication(self)

    def setAuthority(self, authority):
        return _Core.Record_setAuthority(self, authority)

    def authority(self):
        return _Core.Record_authority(self)

    def data(self):
        return _Core.Record_data(self)

    def raw(self):
        return _Core.Record_raw(self)

    def copy(self):
        return _Core.Record_copy(self)

    def clipMask(self):
        return _Core.Record_clipMask(self)

    def saveSpace(self):
        return _Core.Record_saveSpace(self)

    def read(self, _in):
        return _Core.Record_read(self, _in)

    def write(self, out):
        return _Core.Record_write(self, out)

# Register Record in _Core:
_Core.Record_swigregister(Record)

def Record_ClassName():
    return _Core.Record_ClassName()

def Record_TypeInfo():
    return _Core.Record_TypeInfo()

def Record_Cast(*args):
    return _Core.Record_Cast(*args)

def Record_ConstCast(*args):
    return _Core.Record_ConstCast(*args)

ZSS = _Core.ZSS
ZDS = _Core.ZDS
ZDD = _Core.ZDD
RSS = _Core.RSS
RDS = _Core.RDS
RDD = _Core.RDD
TSS = _Core.TSS
TDS = _Core.TDS
ZEP = _Core.ZEP
REP = _Core.REP
EGreensFunctionComponentQuantity = _Core.EGreensFunctionComponentQuantity
class EGreensFunctionComponentNames(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Core.EGreensFunctionComponentNames_swiginit(self, _Core.new_EGreensFunctionComponentNames())

    @staticmethod
    def name(i):
        return _Core.EGreensFunctionComponentNames_name(i)
    __swig_destroy__ = _Core.delete_EGreensFunctionComponentNames

# Register EGreensFunctionComponentNames in _Core:
_Core.EGreensFunctionComponentNames_swigregister(EGreensFunctionComponentNames)

def EGreensFunctionComponentNames_name(i):
    return _Core.EGreensFunctionComponentNames_name(i)

class GreensFunction(BaseObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.GreensFunction_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.GreensFunction_TypeInfo()

    def className(self):
        return _Core.GreensFunction_className(self)

    def typeInfo(self):
        return _Core.GreensFunction_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.GreensFunction_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.GreensFunction_ConstCast(*args)

    def serialize(self, ar):
        return _Core.GreensFunction_serialize(self, ar)

    def __init__(self, *args):
        _Core.GreensFunction_swiginit(self, _Core.new_GreensFunction(*args))
    __swig_destroy__ = _Core.delete_GreensFunction

    def setId(self, id):
        return _Core.GreensFunction_setId(self, id)

    def id(self):
        return _Core.GreensFunction_id(self)

    def setModel(self, model):
        return _Core.GreensFunction_setModel(self, model)

    def model(self):
        return _Core.GreensFunction_model(self)

    def setDistance(self, arg2):
        return _Core.GreensFunction_setDistance(self, arg2)

    def distance(self):
        return _Core.GreensFunction_distance(self)

    def setDepth(self, arg2):
        return _Core.GreensFunction_setDepth(self, arg2)

    def depth(self):
        return _Core.GreensFunction_depth(self)

    def setSamplingFrequency(self, arg2):
        return _Core.GreensFunction_setSamplingFrequency(self, arg2)

    def samplingFrequency(self):
        return _Core.GreensFunction_samplingFrequency(self)

    def setTimeOffset(self, arg2):
        return _Core.GreensFunction_setTimeOffset(self, arg2)

    def timeOffset(self):
        return _Core.GreensFunction_timeOffset(self)

    def length(self, arg2):
        return _Core.GreensFunction_length(self, arg2)

    def data(self, arg2):
        return _Core.GreensFunction_data(self, arg2)

    def setData(self, *args):
        return _Core.GreensFunction_setData(self, *args)

# Register GreensFunction in _Core:
_Core.GreensFunction_swigregister(GreensFunction)

def GreensFunction_ClassName():
    return _Core.GreensFunction_ClassName()

def GreensFunction_TypeInfo():
    return _Core.GreensFunction_TypeInfo()

def GreensFunction_Cast(*args):
    return _Core.GreensFunction_Cast(*args)

def GreensFunction_ConstCast(*args):
    return _Core.GreensFunction_ConstCast(*args)

class GenericRecord(Record):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.GenericRecord_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.GenericRecord_TypeInfo()

    def className(self):
        return _Core.GenericRecord_className(self)

    def typeInfo(self):
        return _Core.GenericRecord_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.GenericRecord_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.GenericRecord_ConstCast(*args)

    def serialize(self, ar):
        return _Core.GenericRecord_serialize(self, ar)

    def __init__(self, *args):
        _Core.GenericRecord_swiginit(self, _Core.new_GenericRecord(*args))
    __swig_destroy__ = _Core.delete_GenericRecord

    def setSamplingFrequency(self, freq):
        return _Core.GenericRecord_setSamplingFrequency(self, freq)

    def data(self, *args):
        return _Core.GenericRecord_data(self, *args)

    def raw(self):
        return _Core.GenericRecord_raw(self)

    def clipMask(self):
        return _Core.GenericRecord_clipMask(self)

    def setData(self, *args):
        return _Core.GenericRecord_setData(self, *args)

    def setClipMask(self, clipMask):
        return _Core.GenericRecord_setClipMask(self, clipMask)

    def dataUpdated(self):
        return _Core.GenericRecord_dataUpdated(self)

    def saveSpace(self):
        return _Core.GenericRecord_saveSpace(self)

    def copy(self):
        return _Core.GenericRecord_copy(self)

    def read(self, _in):
        return _Core.GenericRecord_read(self, _in)

    def write(self, out):
        return _Core.GenericRecord_write(self, out)

# Register GenericRecord in _Core:
_Core.GenericRecord_swigregister(GenericRecord)

def GenericRecord_ClassName():
    return _Core.GenericRecord_ClassName()

def GenericRecord_TypeInfo():
    return _Core.GenericRecord_TypeInfo()

def GenericRecord_Cast(*args):
    return _Core.GenericRecord_Cast(*args)

def GenericRecord_ConstCast(*args):
    return _Core.GenericRecord_ConstCast(*args)

class MessageIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Core.MessageIterator_swiginit(self, _Core.new_MessageIterator(*args))
    __swig_destroy__ = _Core.delete_MessageIterator

    def get(self):
        return _Core.MessageIterator_get(self)

    def __ref__(self):
        return _Core.MessageIterator___ref__(self)

    def step(self):
        return _Core.MessageIterator_step(self)

    def __next__(self):
    	o = self.get()
    	if not o:
    		raise StopIteration

    	self.step()
    	return o

    # for Python 2 compatibility
    def next(self):
    	return self.__next__()


# Register MessageIterator in _Core:
_Core.MessageIterator_swigregister(MessageIterator)

class Message(BaseObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.Message_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.Message_TypeInfo()

    def className(self):
        return _Core.Message_className(self)

    def typeInfo(self):
        return _Core.Message_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.Message_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.Message_ConstCast(*args)

    def serialize(self, ar):
        return _Core.Message_serialize(self, ar)
    __swig_destroy__ = _Core.delete_Message

    def iter(self):
        return _Core.Message_iter(self)

    def size(self):
        return _Core.Message_size(self)

    def empty(self):
        return _Core.Message_empty(self)

    def clear(self):
        return _Core.Message_clear(self)

    def setDataSize(self, size):
        return _Core.Message_setDataSize(self, size)

    def dataSize(self):
        return _Core.Message_dataSize(self)

    def __iter__(self):
    	return self.iter()


# Register Message in _Core:
_Core.Message_swigregister(Message)

def Message_ClassName():
    return _Core.Message_ClassName()

def Message_TypeInfo():
    return _Core.Message_TypeInfo()

def Message_Cast(*args):
    return _Core.Message_Cast(*args)

def Message_ConstCast(*args):
    return _Core.Message_ConstCast(*args)

class DataMessageBase(Message):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def serialize(self, ar):
        return _Core.DataMessageBase_serialize(self, ar)

    def __init__(self):
        _Core.DataMessageBase_swiginit(self, _Core.new_DataMessageBase())
    __swig_destroy__ = _Core.delete_DataMessageBase

    def attach(self, *args):
        return _Core.DataMessageBase_attach(self, *args)

    def detach(self, *args):
        return _Core.DataMessageBase_detach(self, *args)

    def clear(self):
        return _Core.DataMessageBase_clear(self)

    def begin(self, *args):
        return _Core.DataMessageBase_begin(self, *args)

    def end(self, *args):
        return _Core.DataMessageBase_end(self, *args)

    def empty(self):
        return _Core.DataMessageBase_empty(self)

    def size(self):
        return _Core.DataMessageBase_size(self)

# Register DataMessageBase in _Core:
_Core.DataMessageBase_swigregister(DataMessageBase)

class DataMessage(DataMessageBase):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.DataMessage_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.DataMessage_TypeInfo()

    def className(self):
        return _Core.DataMessage_className(self)

    def typeInfo(self):
        return _Core.DataMessage_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.DataMessage_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.DataMessage_ConstCast(*args)

    def __init__(self):
        _Core.DataMessage_swiginit(self, _Core.new_DataMessage())
    __swig_destroy__ = _Core.delete_DataMessage

# Register DataMessage in _Core:
_Core.DataMessage_swigregister(DataMessage)

def DataMessage_ClassName():
    return _Core.DataMessage_ClassName()

def DataMessage_TypeInfo():
    return _Core.DataMessage_TypeInfo()

def DataMessage_Cast(*args):
    return _Core.DataMessage_Cast(*args)

def DataMessage_ConstCast(*args):
    return _Core.DataMessage_ConstCast(*args)

class CharArrayT(Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.CharArrayT_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.CharArrayT_TypeInfo()

    def className(self):
        return _Core.CharArrayT_className(self)

    def typeInfo(self):
        return _Core.CharArrayT_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.CharArrayT_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.CharArrayT_ConstCast(*args)

    def serialize(self, ar):
        return _Core.CharArrayT_serialize(self, ar)
    ArrayType = property(_Core.CharArrayT_ArrayType_get, _Core.CharArrayT_ArrayType_set)

    def __init__(self, *args):
        _Core.CharArrayT_swiginit(self, _Core.new_CharArrayT(*args))
    __swig_destroy__ = _Core.delete_CharArrayT

    def copy(self, dt):
        return _Core.CharArrayT_copy(self, dt)

    def setData(self, size, data):
        return _Core.CharArrayT_setData(self, size, data)

    def data(self):
        return _Core.CharArrayT_data(self)

    def typedData(self, *args):
        return _Core.CharArrayT_typedData(self, *args)

    def size(self):
        return _Core.CharArrayT_size(self)

    def elementSize(self):
        return _Core.CharArrayT_elementSize(self)

    def resize(self, size):
        return _Core.CharArrayT_resize(self, size)

    def clear(self):
        return _Core.CharArrayT_clear(self)

    def fill(self, v):
        return _Core.CharArrayT_fill(self, v)

    def set(self, index, v):
        return _Core.CharArrayT_set(self, index, v)

    def get(self, index):
        return _Core.CharArrayT_get(self, index)

    def append(self, *args):
        return _Core.CharArrayT_append(self, *args)

    def prepend(self, *args):
        return _Core.CharArrayT_prepend(self, *args)

    def slice(self, m, n):
        return _Core.CharArrayT_slice(self, m, n)

    def begin(self, *args):
        return _Core.CharArrayT_begin(self, *args)

    def end(self, *args):
        return _Core.CharArrayT_end(self, *args)

    def impl(self, *args):
        return _Core.CharArrayT_impl(self, *args)

# Register CharArrayT in _Core:
_Core.CharArrayT_swigregister(CharArrayT)

def CharArrayT_ClassName():
    return _Core.CharArrayT_ClassName()

def CharArrayT_TypeInfo():
    return _Core.CharArrayT_TypeInfo()

def CharArrayT_Cast(*args):
    return _Core.CharArrayT_Cast(*args)

def CharArrayT_ConstCast(*args):
    return _Core.CharArrayT_ConstCast(*args)

class IntArrayT(Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.IntArrayT_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.IntArrayT_TypeInfo()

    def className(self):
        return _Core.IntArrayT_className(self)

    def typeInfo(self):
        return _Core.IntArrayT_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.IntArrayT_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.IntArrayT_ConstCast(*args)

    def serialize(self, ar):
        return _Core.IntArrayT_serialize(self, ar)
    ArrayType = property(_Core.IntArrayT_ArrayType_get, _Core.IntArrayT_ArrayType_set)

    def __init__(self, *args):
        _Core.IntArrayT_swiginit(self, _Core.new_IntArrayT(*args))
    __swig_destroy__ = _Core.delete_IntArrayT

    def copy(self, dt):
        return _Core.IntArrayT_copy(self, dt)

    def setData(self, size, data):
        return _Core.IntArrayT_setData(self, size, data)

    def data(self):
        return _Core.IntArrayT_data(self)

    def typedData(self, *args):
        return _Core.IntArrayT_typedData(self, *args)

    def size(self):
        return _Core.IntArrayT_size(self)

    def elementSize(self):
        return _Core.IntArrayT_elementSize(self)

    def resize(self, size):
        return _Core.IntArrayT_resize(self, size)

    def clear(self):
        return _Core.IntArrayT_clear(self)

    def fill(self, v):
        return _Core.IntArrayT_fill(self, v)

    def set(self, index, v):
        return _Core.IntArrayT_set(self, index, v)

    def get(self, index):
        return _Core.IntArrayT_get(self, index)

    def append(self, *args):
        return _Core.IntArrayT_append(self, *args)

    def prepend(self, *args):
        return _Core.IntArrayT_prepend(self, *args)

    def slice(self, m, n):
        return _Core.IntArrayT_slice(self, m, n)

    def begin(self, *args):
        return _Core.IntArrayT_begin(self, *args)

    def end(self, *args):
        return _Core.IntArrayT_end(self, *args)

    def impl(self, *args):
        return _Core.IntArrayT_impl(self, *args)

# Register IntArrayT in _Core:
_Core.IntArrayT_swigregister(IntArrayT)

def IntArrayT_ClassName():
    return _Core.IntArrayT_ClassName()

def IntArrayT_TypeInfo():
    return _Core.IntArrayT_TypeInfo()

def IntArrayT_Cast(*args):
    return _Core.IntArrayT_Cast(*args)

def IntArrayT_ConstCast(*args):
    return _Core.IntArrayT_ConstCast(*args)

class FloatArrayT(Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.FloatArrayT_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.FloatArrayT_TypeInfo()

    def className(self):
        return _Core.FloatArrayT_className(self)

    def typeInfo(self):
        return _Core.FloatArrayT_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.FloatArrayT_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.FloatArrayT_ConstCast(*args)

    def serialize(self, ar):
        return _Core.FloatArrayT_serialize(self, ar)
    ArrayType = property(_Core.FloatArrayT_ArrayType_get, _Core.FloatArrayT_ArrayType_set)

    def __init__(self, *args):
        _Core.FloatArrayT_swiginit(self, _Core.new_FloatArrayT(*args))
    __swig_destroy__ = _Core.delete_FloatArrayT

    def copy(self, dt):
        return _Core.FloatArrayT_copy(self, dt)

    def setData(self, size, data):
        return _Core.FloatArrayT_setData(self, size, data)

    def data(self):
        return _Core.FloatArrayT_data(self)

    def typedData(self, *args):
        return _Core.FloatArrayT_typedData(self, *args)

    def size(self):
        return _Core.FloatArrayT_size(self)

    def elementSize(self):
        return _Core.FloatArrayT_elementSize(self)

    def resize(self, size):
        return _Core.FloatArrayT_resize(self, size)

    def clear(self):
        return _Core.FloatArrayT_clear(self)

    def fill(self, v):
        return _Core.FloatArrayT_fill(self, v)

    def set(self, index, v):
        return _Core.FloatArrayT_set(self, index, v)

    def get(self, index):
        return _Core.FloatArrayT_get(self, index)

    def append(self, *args):
        return _Core.FloatArrayT_append(self, *args)

    def prepend(self, *args):
        return _Core.FloatArrayT_prepend(self, *args)

    def slice(self, m, n):
        return _Core.FloatArrayT_slice(self, m, n)

    def begin(self, *args):
        return _Core.FloatArrayT_begin(self, *args)

    def end(self, *args):
        return _Core.FloatArrayT_end(self, *args)

    def impl(self, *args):
        return _Core.FloatArrayT_impl(self, *args)

# Register FloatArrayT in _Core:
_Core.FloatArrayT_swigregister(FloatArrayT)

def FloatArrayT_ClassName():
    return _Core.FloatArrayT_ClassName()

def FloatArrayT_TypeInfo():
    return _Core.FloatArrayT_TypeInfo()

def FloatArrayT_Cast(*args):
    return _Core.FloatArrayT_Cast(*args)

def FloatArrayT_ConstCast(*args):
    return _Core.FloatArrayT_ConstCast(*args)

class DoubleArrayT(Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.DoubleArrayT_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.DoubleArrayT_TypeInfo()

    def className(self):
        return _Core.DoubleArrayT_className(self)

    def typeInfo(self):
        return _Core.DoubleArrayT_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.DoubleArrayT_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.DoubleArrayT_ConstCast(*args)

    def serialize(self, ar):
        return _Core.DoubleArrayT_serialize(self, ar)
    ArrayType = property(_Core.DoubleArrayT_ArrayType_get, _Core.DoubleArrayT_ArrayType_set)

    def __init__(self, *args):
        _Core.DoubleArrayT_swiginit(self, _Core.new_DoubleArrayT(*args))
    __swig_destroy__ = _Core.delete_DoubleArrayT

    def copy(self, dt):
        return _Core.DoubleArrayT_copy(self, dt)

    def setData(self, size, data):
        return _Core.DoubleArrayT_setData(self, size, data)

    def data(self):
        return _Core.DoubleArrayT_data(self)

    def typedData(self, *args):
        return _Core.DoubleArrayT_typedData(self, *args)

    def size(self):
        return _Core.DoubleArrayT_size(self)

    def elementSize(self):
        return _Core.DoubleArrayT_elementSize(self)

    def resize(self, size):
        return _Core.DoubleArrayT_resize(self, size)

    def clear(self):
        return _Core.DoubleArrayT_clear(self)

    def fill(self, v):
        return _Core.DoubleArrayT_fill(self, v)

    def set(self, index, v):
        return _Core.DoubleArrayT_set(self, index, v)

    def get(self, index):
        return _Core.DoubleArrayT_get(self, index)

    def append(self, *args):
        return _Core.DoubleArrayT_append(self, *args)

    def prepend(self, *args):
        return _Core.DoubleArrayT_prepend(self, *args)

    def slice(self, m, n):
        return _Core.DoubleArrayT_slice(self, m, n)

    def begin(self, *args):
        return _Core.DoubleArrayT_begin(self, *args)

    def end(self, *args):
        return _Core.DoubleArrayT_end(self, *args)

    def impl(self, *args):
        return _Core.DoubleArrayT_impl(self, *args)

# Register DoubleArrayT in _Core:
_Core.DoubleArrayT_swigregister(DoubleArrayT)

def DoubleArrayT_ClassName():
    return _Core.DoubleArrayT_ClassName()

def DoubleArrayT_TypeInfo():
    return _Core.DoubleArrayT_TypeInfo()

def DoubleArrayT_Cast(*args):
    return _Core.DoubleArrayT_Cast(*args)

def DoubleArrayT_ConstCast(*args):
    return _Core.DoubleArrayT_ConstCast(*args)

class ComplexFloatArray(Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.ComplexFloatArray_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.ComplexFloatArray_TypeInfo()

    def className(self):
        return _Core.ComplexFloatArray_className(self)

    def typeInfo(self):
        return _Core.ComplexFloatArray_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.ComplexFloatArray_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.ComplexFloatArray_ConstCast(*args)

    def serialize(self, ar):
        return _Core.ComplexFloatArray_serialize(self, ar)
    ArrayType = property(_Core.ComplexFloatArray_ArrayType_get, _Core.ComplexFloatArray_ArrayType_set)

    def __init__(self, *args):
        _Core.ComplexFloatArray_swiginit(self, _Core.new_ComplexFloatArray(*args))
    __swig_destroy__ = _Core.delete_ComplexFloatArray

    def copy(self, dt):
        return _Core.ComplexFloatArray_copy(self, dt)

    def setData(self, size, data):
        return _Core.ComplexFloatArray_setData(self, size, data)

    def data(self):
        return _Core.ComplexFloatArray_data(self)

    def typedData(self, *args):
        return _Core.ComplexFloatArray_typedData(self, *args)

    def size(self):
        return _Core.ComplexFloatArray_size(self)

    def elementSize(self):
        return _Core.ComplexFloatArray_elementSize(self)

    def resize(self, size):
        return _Core.ComplexFloatArray_resize(self, size)

    def clear(self):
        return _Core.ComplexFloatArray_clear(self)

    def fill(self, v):
        return _Core.ComplexFloatArray_fill(self, v)

    def set(self, index, v):
        return _Core.ComplexFloatArray_set(self, index, v)

    def get(self, index):
        return _Core.ComplexFloatArray_get(self, index)

    def append(self, *args):
        return _Core.ComplexFloatArray_append(self, *args)

    def prepend(self, *args):
        return _Core.ComplexFloatArray_prepend(self, *args)

    def slice(self, m, n):
        return _Core.ComplexFloatArray_slice(self, m, n)

    def begin(self, *args):
        return _Core.ComplexFloatArray_begin(self, *args)

    def end(self, *args):
        return _Core.ComplexFloatArray_end(self, *args)

    def impl(self, *args):
        return _Core.ComplexFloatArray_impl(self, *args)

# Register ComplexFloatArray in _Core:
_Core.ComplexFloatArray_swigregister(ComplexFloatArray)

def ComplexFloatArray_ClassName():
    return _Core.ComplexFloatArray_ClassName()

def ComplexFloatArray_TypeInfo():
    return _Core.ComplexFloatArray_TypeInfo()

def ComplexFloatArray_Cast(*args):
    return _Core.ComplexFloatArray_Cast(*args)

def ComplexFloatArray_ConstCast(*args):
    return _Core.ComplexFloatArray_ConstCast(*args)

class ComplexDoubleArray(Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.ComplexDoubleArray_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.ComplexDoubleArray_TypeInfo()

    def className(self):
        return _Core.ComplexDoubleArray_className(self)

    def typeInfo(self):
        return _Core.ComplexDoubleArray_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.ComplexDoubleArray_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.ComplexDoubleArray_ConstCast(*args)

    def serialize(self, ar):
        return _Core.ComplexDoubleArray_serialize(self, ar)
    ArrayType = property(_Core.ComplexDoubleArray_ArrayType_get, _Core.ComplexDoubleArray_ArrayType_set)

    def __init__(self, *args):
        _Core.ComplexDoubleArray_swiginit(self, _Core.new_ComplexDoubleArray(*args))
    __swig_destroy__ = _Core.delete_ComplexDoubleArray

    def copy(self, dt):
        return _Core.ComplexDoubleArray_copy(self, dt)

    def setData(self, size, data):
        return _Core.ComplexDoubleArray_setData(self, size, data)

    def data(self):
        return _Core.ComplexDoubleArray_data(self)

    def typedData(self, *args):
        return _Core.ComplexDoubleArray_typedData(self, *args)

    def size(self):
        return _Core.ComplexDoubleArray_size(self)

    def elementSize(self):
        return _Core.ComplexDoubleArray_elementSize(self)

    def resize(self, size):
        return _Core.ComplexDoubleArray_resize(self, size)

    def clear(self):
        return _Core.ComplexDoubleArray_clear(self)

    def fill(self, v):
        return _Core.ComplexDoubleArray_fill(self, v)

    def set(self, index, v):
        return _Core.ComplexDoubleArray_set(self, index, v)

    def get(self, index):
        return _Core.ComplexDoubleArray_get(self, index)

    def append(self, *args):
        return _Core.ComplexDoubleArray_append(self, *args)

    def prepend(self, *args):
        return _Core.ComplexDoubleArray_prepend(self, *args)

    def slice(self, m, n):
        return _Core.ComplexDoubleArray_slice(self, m, n)

    def begin(self, *args):
        return _Core.ComplexDoubleArray_begin(self, *args)

    def end(self, *args):
        return _Core.ComplexDoubleArray_end(self, *args)

    def impl(self, *args):
        return _Core.ComplexDoubleArray_impl(self, *args)

# Register ComplexDoubleArray in _Core:
_Core.ComplexDoubleArray_swigregister(ComplexDoubleArray)

def ComplexDoubleArray_ClassName():
    return _Core.ComplexDoubleArray_ClassName()

def ComplexDoubleArray_TypeInfo():
    return _Core.ComplexDoubleArray_TypeInfo()

def ComplexDoubleArray_Cast(*args):
    return _Core.ComplexDoubleArray_Cast(*args)

def ComplexDoubleArray_ConstCast(*args):
    return _Core.ComplexDoubleArray_ConstCast(*args)

class DateTimeArray(Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.DateTimeArray_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.DateTimeArray_TypeInfo()

    def className(self):
        return _Core.DateTimeArray_className(self)

    def typeInfo(self):
        return _Core.DateTimeArray_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.DateTimeArray_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.DateTimeArray_ConstCast(*args)

    def serialize(self, ar):
        return _Core.DateTimeArray_serialize(self, ar)
    ArrayType = property(_Core.DateTimeArray_ArrayType_get, _Core.DateTimeArray_ArrayType_set)

    def __init__(self, *args):
        _Core.DateTimeArray_swiginit(self, _Core.new_DateTimeArray(*args))
    __swig_destroy__ = _Core.delete_DateTimeArray

    def copy(self, dt):
        return _Core.DateTimeArray_copy(self, dt)

    def setData(self, size, data):
        return _Core.DateTimeArray_setData(self, size, data)

    def data(self):
        return _Core.DateTimeArray_data(self)

    def typedData(self, *args):
        return _Core.DateTimeArray_typedData(self, *args)

    def size(self):
        return _Core.DateTimeArray_size(self)

    def elementSize(self):
        return _Core.DateTimeArray_elementSize(self)

    def resize(self, size):
        return _Core.DateTimeArray_resize(self, size)

    def clear(self):
        return _Core.DateTimeArray_clear(self)

    def fill(self, v):
        return _Core.DateTimeArray_fill(self, v)

    def set(self, index, v):
        return _Core.DateTimeArray_set(self, index, v)

    def get(self, index):
        return _Core.DateTimeArray_get(self, index)

    def append(self, *args):
        return _Core.DateTimeArray_append(self, *args)

    def prepend(self, *args):
        return _Core.DateTimeArray_prepend(self, *args)

    def slice(self, m, n):
        return _Core.DateTimeArray_slice(self, m, n)

    def begin(self, *args):
        return _Core.DateTimeArray_begin(self, *args)

    def end(self, *args):
        return _Core.DateTimeArray_end(self, *args)

    def impl(self, *args):
        return _Core.DateTimeArray_impl(self, *args)

# Register DateTimeArray in _Core:
_Core.DateTimeArray_swigregister(DateTimeArray)

def DateTimeArray_ClassName():
    return _Core.DateTimeArray_ClassName()

def DateTimeArray_TypeInfo():
    return _Core.DateTimeArray_TypeInfo()

def DateTimeArray_Cast(*args):
    return _Core.DateTimeArray_Cast(*args)

def DateTimeArray_ConstCast(*args):
    return _Core.DateTimeArray_ConstCast(*args)

class StringArray(Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.StringArray_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.StringArray_TypeInfo()

    def className(self):
        return _Core.StringArray_className(self)

    def typeInfo(self):
        return _Core.StringArray_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.StringArray_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.StringArray_ConstCast(*args)

    def serialize(self, ar):
        return _Core.StringArray_serialize(self, ar)
    ArrayType = property(_Core.StringArray_ArrayType_get, _Core.StringArray_ArrayType_set)

    def __init__(self, *args):
        _Core.StringArray_swiginit(self, _Core.new_StringArray(*args))
    __swig_destroy__ = _Core.delete_StringArray

    def copy(self, dt):
        return _Core.StringArray_copy(self, dt)

    def setData(self, size, data):
        return _Core.StringArray_setData(self, size, data)

    def data(self):
        return _Core.StringArray_data(self)

    def typedData(self, *args):
        return _Core.StringArray_typedData(self, *args)

    def size(self):
        return _Core.StringArray_size(self)

    def elementSize(self):
        return _Core.StringArray_elementSize(self)

    def resize(self, size):
        return _Core.StringArray_resize(self, size)

    def clear(self):
        return _Core.StringArray_clear(self)

    def fill(self, v):
        return _Core.StringArray_fill(self, v)

    def set(self, index, v):
        return _Core.StringArray_set(self, index, v)

    def get(self, index):
        return _Core.StringArray_get(self, index)

    def append(self, *args):
        return _Core.StringArray_append(self, *args)

    def prepend(self, *args):
        return _Core.StringArray_prepend(self, *args)

    def slice(self, m, n):
        return _Core.StringArray_slice(self, m, n)

    def begin(self, *args):
        return _Core.StringArray_begin(self, *args)

    def end(self, *args):
        return _Core.StringArray_end(self, *args)

    def impl(self, *args):
        return _Core.StringArray_impl(self, *args)

# Register StringArray in _Core:
_Core.StringArray_swigregister(StringArray)

def StringArray_ClassName():
    return _Core.StringArray_ClassName()

def StringArray_TypeInfo():
    return _Core.StringArray_TypeInfo()

def StringArray_Cast(*args):
    return _Core.StringArray_Cast(*args)

def StringArray_ConstCast(*args):
    return _Core.StringArray_ConstCast(*args)

class CharArray(CharArrayT):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.CharArray_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.CharArray_TypeInfo()

    def className(self):
        return _Core.CharArray_className(self)

    def typeInfo(self):
        return _Core.CharArray_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.CharArray_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.CharArray_ConstCast(*args)

    def __init__(self, *args):
        _Core.CharArray_swiginit(self, _Core.new_CharArray(*args))
    __swig_destroy__ = _Core.delete_CharArray

    def max(self):
        return _Core.CharArray_max(self)

    def firstMax(self):
        return _Core.CharArray_firstMax(self)

    def absMax(self):
        return _Core.CharArray_absMax(self)

    def min(self):
        return _Core.CharArray_min(self)

    def median(self):
        return _Core.CharArray_median(self)

    def mean(self):
        return _Core.CharArray_mean(self)

    def rms(self, offset=0):
        return _Core.CharArray_rms(self, offset)

    def slice(self, m, n):
        return _Core.CharArray_slice(self, m, n)

    def __iadd__(self, v):
        return _Core.CharArray___iadd__(self, v)

    def __isub__(self, v):
        return _Core.CharArray___isub__(self, v)

    def __imul__(self, v):
        return _Core.CharArray___imul__(self, v)

    def __itruediv__(self, *args):
        return _Core.CharArray___itruediv__(self, *args)
    __idiv__ = __itruediv__



# Register CharArray in _Core:
_Core.CharArray_swigregister(CharArray)

def CharArray_ClassName():
    return _Core.CharArray_ClassName()

def CharArray_TypeInfo():
    return _Core.CharArray_TypeInfo()

def CharArray_Cast(*args):
    return _Core.CharArray_Cast(*args)

def CharArray_ConstCast(*args):
    return _Core.CharArray_ConstCast(*args)

class IntArray(IntArrayT):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.IntArray_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.IntArray_TypeInfo()

    def className(self):
        return _Core.IntArray_className(self)

    def typeInfo(self):
        return _Core.IntArray_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.IntArray_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.IntArray_ConstCast(*args)

    def __init__(self, *args):
        _Core.IntArray_swiginit(self, _Core.new_IntArray(*args))
    __swig_destroy__ = _Core.delete_IntArray

    def max(self):
        return _Core.IntArray_max(self)

    def firstMax(self):
        return _Core.IntArray_firstMax(self)

    def absMax(self):
        return _Core.IntArray_absMax(self)

    def min(self):
        return _Core.IntArray_min(self)

    def median(self):
        return _Core.IntArray_median(self)

    def mean(self):
        return _Core.IntArray_mean(self)

    def rms(self, offset=0):
        return _Core.IntArray_rms(self, offset)

    def slice(self, m, n):
        return _Core.IntArray_slice(self, m, n)

    def __iadd__(self, v):
        return _Core.IntArray___iadd__(self, v)

    def __isub__(self, v):
        return _Core.IntArray___isub__(self, v)

    def __imul__(self, v):
        return _Core.IntArray___imul__(self, v)

    def __itruediv__(self, *args):
        return _Core.IntArray___itruediv__(self, *args)
    __idiv__ = __itruediv__



# Register IntArray in _Core:
_Core.IntArray_swigregister(IntArray)

def IntArray_ClassName():
    return _Core.IntArray_ClassName()

def IntArray_TypeInfo():
    return _Core.IntArray_TypeInfo()

def IntArray_Cast(*args):
    return _Core.IntArray_Cast(*args)

def IntArray_ConstCast(*args):
    return _Core.IntArray_ConstCast(*args)

class FloatArray(FloatArrayT):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.FloatArray_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.FloatArray_TypeInfo()

    def className(self):
        return _Core.FloatArray_className(self)

    def typeInfo(self):
        return _Core.FloatArray_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.FloatArray_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.FloatArray_ConstCast(*args)

    def __init__(self, *args):
        _Core.FloatArray_swiginit(self, _Core.new_FloatArray(*args))
    __swig_destroy__ = _Core.delete_FloatArray

    def max(self):
        return _Core.FloatArray_max(self)

    def firstMax(self):
        return _Core.FloatArray_firstMax(self)

    def absMax(self):
        return _Core.FloatArray_absMax(self)

    def min(self):
        return _Core.FloatArray_min(self)

    def median(self):
        return _Core.FloatArray_median(self)

    def mean(self):
        return _Core.FloatArray_mean(self)

    def rms(self, offset=0):
        return _Core.FloatArray_rms(self, offset)

    def slice(self, m, n):
        return _Core.FloatArray_slice(self, m, n)

    def __iadd__(self, v):
        return _Core.FloatArray___iadd__(self, v)

    def __isub__(self, v):
        return _Core.FloatArray___isub__(self, v)

    def __imul__(self, v):
        return _Core.FloatArray___imul__(self, v)

    def __itruediv__(self, *args):
        return _Core.FloatArray___itruediv__(self, *args)
    __idiv__ = __itruediv__



# Register FloatArray in _Core:
_Core.FloatArray_swigregister(FloatArray)

def FloatArray_ClassName():
    return _Core.FloatArray_ClassName()

def FloatArray_TypeInfo():
    return _Core.FloatArray_TypeInfo()

def FloatArray_Cast(*args):
    return _Core.FloatArray_Cast(*args)

def FloatArray_ConstCast(*args):
    return _Core.FloatArray_ConstCast(*args)

class DoubleArray(DoubleArrayT):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def ClassName():
        return _Core.DoubleArray_ClassName()

    @staticmethod
    def TypeInfo():
        return _Core.DoubleArray_TypeInfo()

    def className(self):
        return _Core.DoubleArray_className(self)

    def typeInfo(self):
        return _Core.DoubleArray_typeInfo(self)

    @staticmethod
    def Cast(*args):
        return _Core.DoubleArray_Cast(*args)

    @staticmethod
    def ConstCast(*args):
        return _Core.DoubleArray_ConstCast(*args)

    def __init__(self, *args):
        _Core.DoubleArray_swiginit(self, _Core.new_DoubleArray(*args))
    __swig_destroy__ = _Core.delete_DoubleArray

    def max(self):
        return _Core.DoubleArray_max(self)

    def firstMax(self):
        return _Core.DoubleArray_firstMax(self)

    def absMax(self):
        return _Core.DoubleArray_absMax(self)

    def min(self):
        return _Core.DoubleArray_min(self)

    def median(self):
        return _Core.DoubleArray_median(self)

    def mean(self):
        return _Core.DoubleArray_mean(self)

    def rms(self, offset=0):
        return _Core.DoubleArray_rms(self, offset)

    def slice(self, m, n):
        return _Core.DoubleArray_slice(self, m, n)

    def __iadd__(self, v):
        return _Core.DoubleArray___iadd__(self, v)

    def __isub__(self, v):
        return _Core.DoubleArray___isub__(self, v)

    def __imul__(self, v):
        return _Core.DoubleArray___imul__(self, v)

    def __itruediv__(self, *args):
        return _Core.DoubleArray___itruediv__(self, *args)
    __idiv__ = __itruediv__



# Register DoubleArray in _Core:
_Core.DoubleArray_swigregister(DoubleArray)

def DoubleArray_ClassName():
    return _Core.DoubleArray_ClassName()

def DoubleArray_TypeInfo():
    return _Core.DoubleArray_TypeInfo()

def DoubleArray_Cast(*args):
    return _Core.DoubleArray_Cast(*args)

def DoubleArray_ConstCast(*args):
    return _Core.DoubleArray_ConstCast(*args)



